# .aws/HandTermCognitoStackTemplate.yml

AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for HandTerm application with HttpOnly Cookies
  and S3 access.

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: HandTermUserPool
      Schema:
        - Name: email
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

  HandTermIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: HandTermIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  HandTermHistoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: handterm
      AccessControl: Private
      VersioningConfiguration:
        Status: Disabled

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: !Sub arn:aws:s3:::handterm/*

  MyLambdaAtEdgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: .aws/http-only-cookies.js
      Description: A Lambda@Edge function for HttpOnly Cookies
      MemorySize: 128
      Timeout: 5
      Role: arn:aws:iam::123456789012:role/your-lambda-execution-role
      Events:
        CloudFrontEvent:
          Type: CloudFront
          Properties:
            Distribution: YourCloudFrontDistributionId
            EventType: viewer-response

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Description: The ID of the Cognito User Pool
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: The ID of the Cognito User Pool Client
  HandTermIdentityPoolId:
    Value: !Ref HandTermIdentityPool
    Description: The ID of the Cognito Identity Pool
  HandTermHistoryBucketName:
    Value: !Ref HandTermHistoryBucket
    Description: The name of the S3 bucket for storing user history
  